# Generated by Django 3.2.9 on 2021-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211124_2214'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopingcart',
            name='unique_cart',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
